### ISSUE TITLE
Feature: Scaling option

### ISSUE THREAD

**Issue by sternschnaube** [NotRyken/EffectTimerPlus#1]

**Comment by NotRyken** [comment]
Since you haven't provided any description I'll go ahead and assume you mean adding an option to change the size of the overlay text.

**Comment by sternschnaube** [comment]
Sorry 😄 
I mean the overall Effect icons, not just the text. Would love to scale it down to 0.5 or even 0.25 😊

**Comment by NotRyken** [comment]
Okay. I'll look into it, but no guarantee beyond that. It isn't currently ETP's responsibility to render the actual icons, just overlay the info text.

**Comment by sternschnaube** [comment]
Thank you - found no other solution for that problem currently.

**Comment by NotRyken** [comment]
Finally added in v1.1.0, available now on [Modrinth](https://modrinth.com/mod/effecttimerplus/versions).
Not sure it was worth the headache but hey it's done now.

**Comment by sternschnaube** [comment]
Thank you so much 😊
