### ISSUE TITLE
Create uk_ua.json

### ISSUE THREAD

**Issue by Tarteroycc** [NotRyken/EffectTimerPlus#2]
### Request Description

your mod is very useful and that's why I wanted you to add a Ukrainian translation so that people with poor English skills can understand the meaning of a certain function

[uk_ua.json](https://github.com/user-attachments/files/16506907/uk_ua.json)

**Comment by NotRyken** [comment]
Added. I'm not sure when it will be released, I generally try to bundle translation changes with other updates.
