### ISSUE TITLE
Game crashes when trying to open mod's configuration menu from mods list

### ISSUE THREAD

**Issue by NovaViper** [NotRyken/EffectTimerPlus#3]
### Mod Version

2.2.1

### Mod Loader

NeoForge 21.1.34

### Minecraft Version

1.21.1

### Bug Description

The game crashes when I try to open the mod's configuration menu. In fact, when I add the mod [BetterModList](https://modrinth.com/mod/better-modlist), it actually tells me that this mod's configuration menu is broken, and it says the exact same error as the one that when the game outputs when it crashed before (without BetterModList installed, so using the built in Mod list from NeoForge).

### Expected Behavior

The menu should just open and not crash; and BetterModList should be able to load it

### Reproduction Steps

1. Launch Minecraft with NeoForge and EffectTimerPlus
2. Open Mods list
3. Open the mod's config menu
4. Bug occurs instantly after pressing the Configuration button

### Log File

https://mclo.gs/nDEYSiA

**Comment by NotRyken** [comment]
Confirmed, thanks for reporting. Looks to be a slight implementation change by NeoForge, no actual code changes but it'll require recompiling to work on 1.21.1 apparently. Not sure about an ETA since I'll be very busy for the next week or so.
