### ISSUE TITLE
choose effect position in inventory

### ISSUE THREAD

**Issue by VaporeonScripts** [NotRyken/EffectTimerPlus#4]
### Request Description

it would be cool to add an option to put the effect on the left in inventories due to jei

### Minecraft Version

1.21.1

**Comment by NotRyken** [comment]
Thanks for the suggestion, however icon repositioning is currently not planned. Consider using an alternative such as [Stylish Effects](https://modrinth.com/mod/stylish-effects) which already provides this capability.

**Comment by VaporeonScripts** [comment]
Alright! Ty
