### ISSUE TITLE
Unexpected warning in the game log

### ISSUE THREAD

**Issue by ItzPiligrim** [NotRyken/EffectTimerPlus#7]
### Mod Version

v2.2.5+1.21-Fabric

### Mod Loader

Fabric

### Minecraft Version

1.21.1

### Bug Description

When starting the game, the mod gives a warning in the log that I do not have YetAnotherConfigLib (YACL) of the required version installed, but this is not the case, I have it, it is installed, and it works, I will add a screenshot below.
![chXMudwMZu](https://github.com/user-attachments/assets/f38c0727-ca09-443d-8257-6c4d165e9329)

### Expected Behavior

Perhaps some bug will be fixed

### Reproduction Steps

You should just run the game with the latest version of the mod, and with the latest version of YACL, however this is happening in my build, I'm not sure if the problem is global or if the mod just conflicts with some other mod

### Log File

[latest.log](https://github.com/user-attachments/files/17997778/latest.log)

**Comment by NotRyken** [comment]
My error, the mod ID should actually be `yet_another_config_lib_v3` not `yacl`. Thanks for reporting.
